//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewNews.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EssayCommunComment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EssayCommunComment()
        {
            this.ECCLike1 = new HashSet<ECCLike>();
            this.ECCReport1 = new HashSet<ECCReport>();
            this.EssayCommunComment1 = new HashSet<EssayCommunComment>();
        }
    
        public int EssayCommunCommentID { get; set; }
        public int EssayCommunID { get; set; }
        public int NewsUserID { get; set; }
        public string ECCContent { get; set; }
        public System.DateTime ECCTime { get; set; }
        public Nullable<int> ECCLike { get; set; }
        public Nullable<int> ECCReport { get; set; }
        public Nullable<int> ECCCID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ECCLike> ECCLike1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ECCReport> ECCReport1 { get; set; }
        public virtual EssayCommun EssayCommun { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EssayCommunComment> EssayCommunComment1 { get; set; }
        public virtual EssayCommunComment EssayCommunComment2 { get; set; }
        public virtual NewsUser NewsUser { get; set; }
    }
}
