//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewNews.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EssayCommun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EssayCommun()
        {
            this.EssayCommunComment = new HashSet<EssayCommunComment>();
        }
    
        public int EssayCommunID { get; set; }
        public string ECTitle { get; set; }
        public string ECContent { get; set; }
        public int ECState { get; set; }
        public int ECClick { get; set; }
        public string ECReturns { get; set; }
        public System.DateTime ECTime { get; set; }
        public int NewsUserID { get; set; }
    
        public virtual NewsUser NewsUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EssayCommunComment> EssayCommunComment { get; set; }
    }
}
