//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewNews.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NewsUser()
        {
            this.ECCLike = new HashSet<ECCLike>();
            this.ECCReport = new HashSet<ECCReport>();
            this.EssayCommun = new HashSet<EssayCommun>();
            this.EssayCommunComment = new HashSet<EssayCommunComment>();
            this.EssayCommunFalse = new HashSet<EssayCommunFalse>();
            this.NCLike = new HashSet<NCLike>();
            this.NCReport = new HashSet<NCReport>();
            this.NewsComment = new HashSet<NewsComment>();
            this.WCCLike = new HashSet<WCCLike>();
            this.WCCReport = new HashSet<WCCReport>();
            this.WriterCommunComment = new HashSet<WriterCommunComment>();
        }
    
        public int NewsUserID { get; set; }
        public string NewsUserAccount { get; set; }
        public string NewsUserPwd { get; set; }
        public string NewsUserName { get; set; }
        public string NewsUserImage { get; set; }
        public string NewsUserSex { get; set; }
        public string NewsUserMotto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ECCLike> ECCLike { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ECCReport> ECCReport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EssayCommun> EssayCommun { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EssayCommunComment> EssayCommunComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EssayCommunFalse> EssayCommunFalse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NCLike> NCLike { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NCReport> NCReport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewsComment> NewsComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WCCLike> WCCLike { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WCCReport> WCCReport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WriterCommunComment> WriterCommunComment { get; set; }
    }
}
