//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewNews.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsFalse
    {
        public int NewsFalseID { get; set; }
        public string NewsFalseTitle { get; set; }
        public string NewsFalseImage { get; set; }
        public string NewsFalseContent { get; set; }
        public Nullable<System.DateTime> NewsFalseTime { get; set; }
        public Nullable<int> NewsFalseClick { get; set; }
        public Nullable<int> EditorID { get; set; }
    
        public virtual Editor Editor { get; set; }
    }
}
