//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewNews.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ViewNewsEntities1 : DbContext
    {
        public ViewNewsEntities1()
            : base("name=ViewNewsEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ECCLike> ECCLike { get; set; }
        public virtual DbSet<ECCReport> ECCReport { get; set; }
        public virtual DbSet<Editor> Editor { get; set; }
        public virtual DbSet<EssayCommun> EssayCommun { get; set; }
        public virtual DbSet<EssayCommunComment> EssayCommunComment { get; set; }
        public virtual DbSet<EssayCommunFalse> EssayCommunFalse { get; set; }
        public virtual DbSet<NCLike> NCLike { get; set; }
        public virtual DbSet<NCReport> NCReport { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<NewsComment> NewsComment { get; set; }
        public virtual DbSet<NewsFalse> NewsFalse { get; set; }
        public virtual DbSet<NewsUser> NewsUser { get; set; }
        public virtual DbSet<WCCLike> WCCLike { get; set; }
        public virtual DbSet<WCCReport> WCCReport { get; set; }
        public virtual DbSet<Writer> Writer { get; set; }
        public virtual DbSet<WriterCommun> WriterCommun { get; set; }
        public virtual DbSet<WriterCommunComment> WriterCommunComment { get; set; }
        public virtual DbSet<WriterCommunFalse> WriterCommunFalse { get; set; }
    }
}
