//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewNews.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WriterCommunComment
    {
        public int WriterCommunCommentID { get; set; }
        public int WriterCommunID { get; set; }
        public int NewsUserID { get; set; }
        public string WCCContent { get; set; }
        public System.DateTime WCCTime { get; set; }
    
        public virtual NewsUser NewsUser { get; set; }
        public virtual WriterCommun WriterCommun { get; set; }
    }
}
