//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewNews.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WriterCommunFalse
    {
        public int WriterCommunFalseID { get; set; }
        public string WCFTitle { get; set; }
        public string WCFImage { get; set; }
        public string WCFContent { get; set; }
        public Nullable<System.DateTime> WCFTime { get; set; }
        public Nullable<int> WCFClick { get; set; }
        public Nullable<int> WriterID { get; set; }
        public Nullable<int> EditorID { get; set; }
    
        public virtual Editor Editor { get; set; }
        public virtual Writer Writer { get; set; }
    }
}
